# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-16 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField(editable=False)),
                ('name', models.CharField(default='To-Do Label', max_length=500)),
                ('quad', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('0', 'Urgent & Important'), ('1', 'Urgent'), ('2', 'Important'), ('3', 'Other')], default='0', max_length=100)),
                ('completed', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['quad', 'category', 'order'],
            },
        ),
    ]
