# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-17 15:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['quad', 'category', 'ordering']},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='order',
            new_name='ordering',
        ),
    ]
